### ISSUE TITLE
the result of run_example.sh fig4 is strange

### ISSUE THREAD

**Issue by WangMengxiao319** [citiususc/construe#12]
## Describe the issue

I have entered `bash run_example.sh fig4` in my terminal. 

**Actual Behavior:**
And the results turn out as follow: 
![fig4](https://github.com/citiususc/construe/assets/68960630/d3d2bbb6-a0d1-4d58-a1b4-2108700b8447)

It seems that it's different from the image in the *readme.md*, 

- **The horizontal axis doesn't start from 0, and it appears that the signal has been truncated**

- **The top is a little bit strange. There is a circle on the top, is that normal?**

**Expected Behavior:**

As readme.md reveals, the expected result is 

![example](https://github.com/citiususc/construe/assets/68960630/31ebbfb3-0ac3-461f-ab1f-657d6a09fb37)

## Environment

Operating System: Linux

Python Version: Python 3.8.18

Package Name and Version:

- brotlipy==0.7.0
- fonttools==4.25.0
- matplotlib==3.3.4
- munkres==1.1.4
- numpy==1.19.5
- ply==3.11
- pyperclip==1.8.2
- PyQt5-sip==12.11.0
- scikit-learn==0.22.1
- scipy==1.10.1

**Comment by tomas-teijeiro** [comment]
Thanks for reporting!

Indeed, the figure you are obtaining is basically the same as the one you expected, but you need to reduce the zoom level to see the whole signal fragment. We did it in that way to make it easier to visualize the reasoning process, with all the details on the predicted/subsumed observations. 

The circle is used to highlight the focus of attention at each step. In your case, it is still on the top-level rhythm because it already covers the full set of initial observations, and therefore it is as good as the explanation plotted in the "expected behavior". 

Anyway, I can confirm that the software is working properly on your machine 🙂.

**Comment by WangMengxiao319** [comment]
Thanks for your reply, I have got it!
